### ISSUE TITLE
Question for The Training Time

### ISSUE THREAD

**Issue by Chantec** [wwangcece/SGDM#2]
Dear author
thank you very much for your excellent work. I would like to know how long it took you to train on two RTX 3090 GPUs?

**Comment by wwangcece** [comment]
Hello, thanks for attention! We trained 150K steps on two RTX 3090 GPUS to reach convergence, which took about two days in total. As for the normalizing flow model, it can converge quickly in less than two hours.

**Comment by wwangcece** [comment]
Hello, thanks for attention! We trained 150K steps on two RTX 3090 GPUS to reach convergence, which took about two days in total. As for the normalizing flow model, it can converge quickly in less than two hours.

**Comment by Chantec** [comment]
> Hello, thanks for attention! We trained 150K steps on two RTX 3090 GPUS to reach convergence, which took about two days in total. As for the normalizing flow model, it can converge quickly in less than two hours.

Thanks for your reply! Looking forward to your training code!
