### ISSUE TITLE
about vector maps

### ISSUE THREAD

**Issue by xiaodu-1** [wwangcece/SGDM#3]
Hello, I have two questions: 
Firstly, how can I gain the vector maps of my personal dataset and what is the specific method? 
Secondly, what is the input for the model during inference, and do we need to input the vector maps together?
Thank you！！

**Comment by wwangcece** [comment]
Our vector images were downloaded from the [Maptile](https://www.maptiler.com/) website. And the downloading script is here:[dataset](https://drive.google.com/file/d/1HIrHj1qurTTuRyUpYNZRxbmpjUfdO6dN/view?usp=drive_link). You need to sign up for a Maptile account, and then fill your own key into the script to download tile data for satellite images and vector maps.

**Comment by wwangcece** [comment]
To inference, you need to modify the val_dataset configuration file and enter the path of the configuration file into the inference.py script (--val_config hyperparameter).
