### ISSUE TITLE
sample a random timestep

### ISSUE THREAD

**Issue by Chantec** [wwangcece/SGDM#7]
May I ask if any sampling strategy is used for t during the training phase?

**Comment by wwangcece** [comment]
During the training period, we sample t uniformly from [0, 1000].

**Comment by Chantec** [comment]
> During the training period, we sample t uniformly from [0, 1000].

Have you encountered the situation in the t2i-adapter? They found that adapter had a greater influence on conditions in the first few steps of sampling, so they used cubic sampling, which is more likely to train the model in the first few steps of sampling.

**Comment by wwangcece** [comment]
> > During the training period, we sample t uniformly from [0, 1000].
> 
> Have you encountered the situation in the t2i-adapter? They found that adapter had a greater influence on conditions in the first few steps of sampling, so they used cubic sampling, which is more likely to train the model in the first few steps of sampling.

Of course, perhaps the cubic sampling method of the T2-Adapter will produce better results. However, for the super-resolution task, the low-resolution image already contains enough information, which is the difference between it and the generation task. So I don't think cubic's sampling method will make a huge difference in performance.

**Comment by Chantec** [comment]
> > > During the training period, we sample t uniformly from [0, 1000].
> > 
> > 
> > Have you encountered the situation in the t2i-adapter? They found that adapter had a greater influence on conditions in the first few steps of sampling, so they used cubic sampling, which is more likely to train the model in the first few steps of sampling.
> 
> Of course, perhaps the cubic sampling method of the T2-Adapter will produce better results. However, for the super-resolution task, the low-resolution image already contains enough information, which is the difference between it and the generation task. So I don't think cubic's sampling method will make a huge difference in performance.

OK，Thanks for your reply!
