### ISSUE TITLE
about openstreetmap api

### ISSUE THREAD

**Issue by RenshengJi** [wwangcece/SGDM#8]
Hello, I used the openstreetmap api you provided to get text in the vector map, such as the road name. How can I eliminate this?
![18_129014_81584](https://github.com/user-attachments/assets/c99be939-5fe3-4c67-8e43-df546acbcd93) ![18_127646_81715](https://github.com/user-attachments/assets/8618d220-2dd8-4989-8361-edfda2df5488)

**Comment by RenshengJi** [comment]
I used 'openstreetmap': 'https://tile-a.openstreetmap.fr/hot/{z}/{x}/{y}.png'

**Comment by wwangcece** [comment]
Thank you for your attention. In fact, I ran into this problem when I first tried to collect data, and found that all **free** apis have this problem. That's why I started using the **paid** Maptile platform to create datasets.

> I used 'openstreetmap': '[https://tile-a.openstreetmap.fr/hot/{z}/{x}/{y}.png](https://tile-a.openstreetmap.fr/hot/%7Bz%7D/%7Bx%7D/%7By%7D.png)'

**Comment by RenshengJi** [comment]
I see. Thank you for your reply
