### ISSUE TITLE
About time alignment

### ISSUE THREAD

**Issue by RenshengJi** [wwangcece/SGDM#9]
Are the World Imagery, Open Street Map, Sentinel-2 guaranteed to be aligned in time? Because in theory, the content of the picture may be different at different times (moving vehicles and pedestrians, buildings under construction).

**Comment by wwangcece** [comment]
Since we cannot obtain the time label of the vector map, time alignment is not possible in this study. We can only ensure rough time alignment by getting the latest images from different platforms.

> Are the World Imagery, Open Street Map, Sentinel-2 guaranteed to be aligned in time? Because in theory, the content of the picture may be different at different times (moving vehicles and pedestrians, buildings under construction).

**Comment by wwangcece** [comment]
However, even in the case of time misalignment, the introduction of vector maps still works. Therefore, we believe that time-aligned vector images can bring more gain to the super-resolution reconstruction process.

**Comment by RenshengJi** [comment]
I see. Thank you for your reply.
